### ISSUE TITLE
Memory consumption and continuous annotation

### ISSUE THREAD

**Issue by demodw** [alipazokit/RHE-mc#5]
Hi,

In Pazokitoroudi et al (2020), you write that "Further, due to its use of a streaming implementation that only requires the genotypes to be operated on once, the memory requirement of RHE-mc is modest: all experiments required <60 GB". Right now I am trying to fit a model with 60K individuals, ~450K SNPs and 22 variance components. It's currently using 30GB of RAM. If I use annotation from e.g. LDScore for the 1.1M HM3 SNPs, it's at well over 60+gb for the same sample size. How did you achieve this low memory consumption from the analysis performed in the article? I noticed there's a "-mem" flag in the code but it doesn't do anything and seems to be disabled in the source code.

Second, when I try to add continuous annotation I just seem to get a segfault. As I understand it from Pazokitoroudi et al (2020), both binary and continuous annotations are supposed to be implemented.

Thanks in advance.

**Comment by alipazokit** [comment]
Hi,
thank you for your interest in using our software.

I just uploaded the highly memory efficient version: 

./RHEmc_mem <command_line arguments> (-jn 1000 is recommended in this setting, specifically when there are many overlapping annotations)


Regarding your questions: 

1) The previous version (RHEmc) is still memory efficient for the small set of  non-overlapping annotation. In SI of our paper, we showed the memory usage is O(JKBN) + the size of genotype per stream block (which is same as jackknife block size). In the paper, in running time comparison, we do not have any overlapping annotations.

2) We implemented the version supporting continuous annotations, but we realized it would be better to partition SNPs based on the value of your interest and form the binary annotations. For example, the way we defined LD score or MAF bins. The current public versions does not support continuous annotations. 


Please let me know if you have any other questions, and sorry for the inconvenience !

**Comment by demodw** [comment]
Hi,

Thanks for the update! I'll try it out.

Re the continuous annotations, do you mean better in terms of power to detect enrichment? I think for something like tissue annotations using e.g. https://github.com/perslab/CELLECT with GTEX would add ~54 tissues x 10 bins = 570 annotations. Is this feasible?

Thanks.

**Comment by demodw** [comment]
The new version seems to have improved memory usage by a lot, thanks!

One more question that came into mind, have you done have simulations as to how precise the estimate of heritability should be before it makes sense to do partitioned heritability? In the LDSC-S article they suggest Z > 7. When I try to partition heritability just into chromosomes (i.e. 22 VCs), I get enrichments in the order of ~1-2 and SEs in the order of 300-400, even if the phenotype has a Z-score = 13. Do you have any recommendations / advice on this?

Thanks

**Comment by alipazokit** [comment]
We have not done that specific expermient. I think, it really depends on the distribution of causal SNPs. For example if there is a phenotype where most of SNPs are causal with very low total h^2, then it would be hard to observe statically significant signal for a specific annotation. On the other hand, if there is only a few causal SNPs , then it would be likely to observe annotation-specific signal. So it is not only a function of total h^2, it also depends on per-SNP heritability of causal SNPs.

I would be happy to look at the output file where you got enrichment with very high SE, it looks problematic. You can share them with me by email (alipazokit@gmail.com).

For continuous annotation, we would recommend using a sufficiently large number of discrete annotations (e.g. based on quartile of the values of a continuous annotation) to allow for a flexible relationship between effect size and annotation value (while assuming that heritability is constant within a category).

let me know if you have any other questions !
